version: "3.8"

x-default: &default
  networks:
    - bal_network
  restart: unless-stopped

x-node-image: &node-image
  <<: *default
  build:
    context: .
    dockerfile: Dockerfile
    target: builder_root
  volumes:
    - ./:/app/:z

services:
  reverse_proxy:
    <<: *default
    image: ghcr.io/mission-apprentissage/mna_reverse_proxy:0.0.4-beta.12
    ports:
      - 80:80
      - 443:443
    environment:
      - SERVER_NAME=localhost
      - NGINX_ALWAYS_TLS_REDIRECT=false

  ui:
    <<: *node-image
    stdin_open: true
    working_dir: "/app/ui"
    expose:
      - "3000"
    command: ["yarn", "dev"]

  server:
    <<: *node-image
    depends_on:
      mongodb:
        condition: service_healthy
      smtp:
        condition: service_started
    env_file: .env_server
    volumes:
      - ./:/app/:z
      - bal_server_data:/data
    working_dir: "/app/server"
    expose:
      - "5000"
    command: ["yarn", "dev"]

  processor:
    <<: *node-image
    command: ["yarn", "cli", "processor"]
    env_file: .env_server
    volumes:
      - ./:/app/:z
      - bal_server_data:/data
    depends_on:
      mongodb:
        condition: service_healthy
      clamav:
        condition: service_healthy
    working_dir: "/app/server"
    expose:
      - "5000"

  mongodb:
    <<: *default
    image: mongo:6.0.2-focal
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - bal_mongodb_data:/data
    healthcheck:
      test:
        ["CMD", "mongosh", "--eval", '''db.runCommand("ping").ok''', "--quiet"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 10s

  clamav:
    <<: *default
    image: clamav/clamav:latest
    healthcheck:
      test: ["CMD", "/usr/local/bin/clamdcheck.sh"]
      interval: 60s
      retries: 3
      start_period: 6m
    volumes:
      - bal_clamav_data:/var/lib/clamav

  smtp:
    <<: *default
    image: axllent/mailpit:v1.5.5
    ports:
      - 1025:1025
      - 8025:8025
    environment:
      - MP_DATA_FILE=/data/mailpit.db
    volumes:
      - bal_smtp_data:/data

volumes:
  bal_mongodb_data:
    driver: local
    name: bal_mongodb_data
  bal_server_data:
    driver: local
    name: bal_server_data
  bal_smtp_data:
    driver: local
    name: bal_smtp_data
  bal_clamav_data:
    driver: local
    name: bal_clamav_data

networks:
  bal_network:
    name: bal_network
