services:
  mongodb:
    build: ./.infra/local
    restart: unless-stopped
    hostname: mongodb
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - bal_mongodb_data:/data
    healthcheck:
      test: ["CMD", "mongosh", "--eval", '''db.runCommand("ping").ok''', "--quiet"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 10s

  clamav:
    image: clamav/clamav:latest
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "/usr/local/bin/clamdcheck.sh"]
      interval: 60s
      retries: 3
      start_period: 6m
    ports:
      - 3310:3310
    volumes:
      - bal_clamav_data:/var/lib/clamav

  smtp:
    image: axllent/mailpit:v1.5.5
    restart: unless-stopped
    ports:
      - 1025:1025
      - 8025:8025
    environment:
      - MP_DATA_FILE=/data/mailpit.db
    volumes:
      - bal_smtp_data:/data

volumes:
  bal_mongodb_data:
    driver: local
    name: bal_mongodb_data
  bal_smtp_data:
    driver: local
    name: bal_smtp_data
  bal_clamav_data:
    driver: local
    name: bal_clamav_data
