version: "3.8"

services:
  server:
    ports:
      - "9229:9229"
    command: sh -c "yarn build && node --inspect=0.0.0.0:9229 --enable-source-maps dist/index.js start"

  processor:
    ports:
      - "9230:9230"
    command: sh -c "yarn build && node --inspect-brk=0.0.0.0:9230 --enable-source-maps dist/index.js processor"
