version: "2.4"
services:
  repo_modules:
    restart: "no"
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/app/:z

  reverse_proxy:
    image: bal_reverse_proxy
    container_name: bal_reverse_proxy
    mem_limit: 256m
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    networks:
      - bal_network
    depends_on:
      - server
      - ui
    environment:
      - PARANOIA=1
      - ANOMALY_INBOUND=5
      - ANOMALY_OUTBOUND=4
      - REPORTING_LEVEL=4
      - DNS_SERVER=127.0.0.11
      - PROXY=1
      - SERVERNAME=localhost
      - ACCESSLOG=/data/access.log
      - ERRORLOG=/data/error.log
      - LOGLEVEL=warn
      - NGINX_ALWAYS_TLS_REDIRECT=false
      - ALLOWED_METHODS=GET HEAD POST OPTIONS PUT DELETE
    volumes:
      - bal_nginx_data:/data:z
      - ./reverse_proxy/dev/includes:/etc/nginx/templates/includes/env
    build:
      context: reverse_proxy

  ui:
    image: bal_ui
    container_name: bal_ui
    mem_limit: 2g
    stdin_open: true
    networks:
      - bal_network
    depends_on:
      - server
    environment:
      - NEXT_SERVER_URI=http://server:5000
      - NEXT_PUBLIC_SENTRY_DSN=
      - NEXT_PUBLIC_ENV=dev
      - NEXT_PUBLIC_BASE_HOST=localhost
      - NEXT_PUBLIC_METABASE_URL=https://localhost/metabase
      - NEXT_PUBLIC_METABASE_SECRET_KEY=
    volumes:
      - ./:/app/:z
    build:
      context: .
      dockerfile: ui/Dockerfile.dev

  server:
    image: bal_server
    container_name: bal_server
    restart: "no"
    mem_limit: 1g
    networks:
      - bal_network
    depends_on:
      - mongodb
      - smtp
    environment:
      - MNA_BAL_MONGODB_URI=mongodb://mongodb:27017/mna-bal?retryWrites=true&w=majority
      - MNA_BAL_ENV=dev
      - MNA_BAL_LOG_LEVEL=debug
      - MNA_BAL_LOG_DESTINATIONS=stdout,mongodb
      - MNA_BAL_SMTP_HOST=smtp
      - MNA_BAL_SMTP_PORT=1025
      - MNA_BAL_AUTH_ACTIVATION_JWT_SECRET=secret
      - MNA_BAL_AUTH_API_TOKEN_JWT_SECRET=secret
      - MNA_BAL_AUTH_PASSWORD_JWT_SECRET=secret
      - MNA_BAL_SENTRY_DSN=
    volumes:
      - ./:/app/:z
      - bal_server_data:/data:z
    build:
      context: .
      dockerfile: server/Dockerfile.dev

  mongodb:
    image: mongo:6.0.2-focal
    container_name: bal_mongodb
    mem_limit: 2g
    restart: unless-stopped
    depends_on:
      repo_modules:
        condition: service_completed_successfully
    ports:
      - "127.0.0.1:27017:27017"
    networks:
      - bal_network
    volumes:
      - bal_mongodb_data:/data

  metabase:
    image: metabase/metabase:v0.46.0
    container_name: bal_metabase
    mem_limit: 2g
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - bal_network
    environment:
      JAVA_TIMEZONE: Europe/Paris
      MB_DB_FILE: /data/metabase/metabase.db
      MB_SITE_LOCALE: fr
      MB_SITE_URL: http://localhost/metabase
    volumes:
      - bal_metabase_data:/data/metabase
      - bal_metabase_data:/data/backups

  clamav:
    image: clamav/clamav:0.105.1
    container_name: bal_clamav
    mem_limit: 2g
    restart: unless-stopped
    ports:
      - 3310:3310
    networks:
      - bal_network
    healthcheck:
      test: ["CMD", "/usr/local/bin/clamdcheck.sh"]
      interval: 60s
      retries: 3
      start_period: 120s
  
  smtp:
    image: mailhog/mailhog
    container_name: bal_smtp
    mem_limit: 128m
    ports:
      - 1025:1025
    networks:
      - bal_network
    environment:
      - MH_UI_WEB_PATH=smtp
      - MH_STORAGE=mongodb
      - MH_MONGO_URI=mongodb:27017
      - MH_MONGO_DB=mna-bal
      - MH_MONGO_COLLECTION=mailhog
    depends_on:
      - mongodb

volumes:
  bal_mongodb_data:
    driver: local
    name: bal_mongodb_data
  bal_metabase_data:
    driver: local
    name: bal_metabase_data
  bal_nginx_data:
    driver: local
    name: bal_nginx_data
  bal_server_data:
    driver: local
    name: bal_server_data

networks:
  bal_network:
    name: bal_network

