version: "3.8"

services:
  repo_modules:
    restart: "no"
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/app/:z

  reverse_proxy:
    ports:
      - 80:80
      - 443:443
    networks:
      - bal_network
    environment:
      - PARANOIA=1
      - ANOMALY_INBOUND=5
      - ANOMALY_OUTBOUND=4
      - REPORTING_LEVEL=4
      - DNS_SERVER=127.0.0.11
      - PROXY=1
      - SERVERNAME=localhost
      - LOGLEVEL=warn
      - NGINX_ALWAYS_TLS_REDIRECT=false
      - ALLOWED_METHODS=GET HEAD POST OPTIONS PUT DELETE
    volumes:
      - bal_nginx_data:/data
    build:
      context: reverse_proxy

  ui:
    stdin_open: true
    networks:
      - bal_network
    environment:
      - NEXT_SERVER_URI=http://server:5000
      - NEXT_PUBLIC_SENTRY_DSN=
      - NEXT_PUBLIC_ENV=dev
      - NEXT_PUBLIC_BASE_HOST=localhost
      - NEXT_PUBLIC_METABASE_URL=https://localhost/metabase
      - NEXT_PUBLIC_METABASE_SECRET_KEY=
    volumes:
      - ./:/app/:z
    build:
      context: .
      dockerfile: ui/Dockerfile.dev

  server:
    networks:
      - bal_network
    depends_on:
      - mongodb
      - smtp
    environment:
      - MNA_BAL_MONGODB_URI=mongodb://mongodb:27017/mna-bal?retryWrites=true&w=majority
      - MNA_BAL_ENV=dev
      - MNA_BAL_LOG_LEVEL=debug
      - MNA_BAL_LOG_DESTINATIONS=stdout,mongodb
      - MNA_BAL_SMTP_HOST=smtp
      - MNA_BAL_SMTP_PORT=1025
      - MNA_BAL_AUTH_ACTIVATION_JWT_SECRET=secret
      - MNA_BAL_AUTH_API_TOKEN_JWT_SECRET=secret
      - MNA_BAL_AUTH_PASSWORD_JWT_SECRET=secret
      - MNA_BAL_SENTRY_DSN=
    volumes:
      - ./:/app/:z
      - bal_server_data:/data
    build:
      context: .
      dockerfile: server/Dockerfile.dev

  processor:
    command: ["yarn", "cli", "processor"]
    deploy:
      resources:
        limits:
          memory: 2g
    restart: unless-stopped
    networks:
      - bal_network
    depends_on:
      - mongodb
      - clamav
    environment:
      - MNA_BAL_MONGODB_URI=mongodb://mongodb:27017/mna-bal?retryWrites=true&w=majority
      - MNA_BAL_ENV=dev
      - MNA_BAL_LOG_LEVEL=debug
      - MNA_BAL_LOG_DESTINATIONS=stdout,mongodb
      - MNA_BAL_SENTRY_DSN=
    volumes:
      - ./:/app/:z
      - bal_server_data:/data
    build:
      context: .
      dockerfile: server/Dockerfile.dev

  mongodb:
    image: mongo:6.0.2-focal
    deploy:
      resources:
        limits:
          memory: 2g
    restart: unless-stopped
    depends_on:
      repo_modules:
        condition: service_completed_successfully
    ports:
      - "127.0.0.1:27017:27017"
    networks:
      - bal_network
    volumes:
      - bal_mongodb_data:/data

  metabase:
    image: metabase/metabase:v0.46.0
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - bal_network
    environment:
      JAVA_TIMEZONE: Europe/Paris
      MB_DB_FILE: /data/metabase/metabase.db
      MB_SITE_LOCALE: fr
      MB_SITE_URL: http://localhost/metabase
    volumes:
      - bal_metabase_data:/data/metabase
      - bal_metabase_data:/data/backups

  clamav:
    image: clamav/clamav:latest
    restart: unless-stopped
    networks:
      - bal_network
    healthcheck:
      test: ["CMD", "/usr/local/bin/clamdcheck.sh"]
      interval: 60s
      retries: 3
      start_period: 120s
  
  smtp:
    image: axllent/mailpit:v1.5.5
    ports:
      - 1025:1025
    networks:
      - bal_network
    environment:
      - MP_DATA_FILE=/data/mailpit.db
    volumes:
      - bal_smtp_data:/data
    depends_on:
      - mongodb

volumes:
  bal_mongodb_data:
    driver: local
    name: bal_mongodb_data
  bal_metabase_data:
    driver: local
    name: bal_metabase_data
  bal_nginx_data:
    driver: local
    name: bal_nginx_data
  bal_server_data:
    driver: local
    name: bal_server_data
  bal_smtp_data:
    driver: local
    name: bal_smtp_data


networks:
  bal_network:
    name: bal_network

