- name: Stoppe tous les conteneurs applicatifs
  shell: "bash /opt/bal/stop-app.sh"

- name: "Clone du repository (branche : {{ git_revision }})"
  git:
    repo: "https://github.com/mission-apprentissage/bal.git"
    version: "{{ git_revision }}"
    force: yes
    accept_hostkey: yes
    dest: /opt/bal/repository

- name: Création des répertoires 'overrides'
  file:
    path: "/opt/bal/.overrides/{{ item.path }}/"
    state: directory
  with_filetree:
    - app/.overrides/common/
    - app/.overrides/{{ env_type }}/
  when: item.state == 'directory'

- name: Copie des fichiers 'overrides'
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "/opt/bal/.overrides/{{ item.path }}"
  with_filetree:
    - app/.overrides/common/
    - app/.overrides/{{ env_type }}/
  when: item.state == 'file' and ".DS_Store" not in item.path

- name: Root only pour tous les répertoires applicatifs
  file:
    path: "{{item}}"
    state: directory
    owner: root
    group: root
    mode: 770
  with_items:
    - "/opt/bal/tools"
    - "/opt/bal/repository"
    - "/opt/bal/data"
    - "/opt/bal/backups"
    - "/opt/bal/.overrides"

- name: Add cron to rotate nginx files
  ansible.builtin.cron:
    name: "rotate_nginx_log_files"
    minute: "0"
    hour: "1"
    job: "bash /opt/bal/tools/rotate-nginx-log-files.sh >> /var/log/cron.log 2>&1"
# - name: Add cron to reload app automatically
#   when: env_type == "recette"
#   ansible.builtin.cron:
#     name: "reload-app"
#     minute: "*/1"
#     hour: 8-20
#     weekday: 1-5
#     job: "bash /opt/bal/reload-app.sh >> /var/log/cron.log 2>&1"
