export const departements = {
  "01": { code: "01", name: "Ain" },
  "02": { code: "02", name: "Aisne" },
  "03": { code: "03", name: "Allier" },
  "04": { code: "04", name: "Alpes-de-Haute-Provence" },
  "05": { code: "05", name: "Hautes-Alpes" },
  "06": { code: "06", name: "Alpes-Maritimes" },
  "07": { code: "07", name: "Ardèche" },
  "08": { code: "08", name: "Ardennes" },
  "09": { code: "09", name: "Ariège" },
  "10": { code: "10", name: "Aube" },
  "11": { code: "11", name: "Aude" },
  "12": { code: "12", name: "Aveyron" },
  "13": { code: "13", name: "Bouches-du-Rhône" },
  "14": { code: "14", name: "Calvados" },
  "15": { code: "15", name: "Cantal" },
  "16": { code: "16", name: "Charente" },
  "17": { code: "17", name: "Charente-Maritime" },
  "18": { code: "18", name: "Cher" },
  "19": { code: "19", name: "Corrèze" },
  "2A": { code: "2A", name: "Corse-du-Sud" },
  "2B": { code: "2B", name: "Haute-Corse" },
  "21": { code: "21", name: "Côte-d'Or" },
  "22": { code: "22", name: "Côtes-d'Armor" },
  "23": { code: "23", name: "Creuse" },
  "24": { code: "24", name: "Dordogne" },
  "25": { code: "25", name: "Doubs" },
  "26": { code: "26", name: "Drôme" },
  "27": { code: "27", name: "Eure" },
  "28": { code: "28", name: "Eure-et-Loir" },
  "29": { code: "29", name: "Finistère" },
  "30": { code: "30", name: "Gard" },
  "31": { code: "31", name: "Haute-Garonne" },
  "32": { code: "32", name: "Gers" },
  "33": { code: "33", name: "Gironde" },
  "34": { code: "34", name: "Hérault" },
  "35": { code: "35", name: "Ille-et-Vilaine" },
  "36": { code: "36", name: "Indre" },
  "37": { code: "37", name: "Indre-et-Loire" },
  "38": { code: "38", name: "Isère" },
  "39": { code: "39", name: "Jura" },
  "40": { code: "40", name: "Landes" },
  "41": { code: "41", name: "Loir-et-Cher" },
  "42": { code: "42", name: "Loire" },
  "43": { code: "43", name: "Haute-Loire" },
  "44": { code: "44", name: "Loire-Atlantique" },
  "45": { code: "45", name: "Loiret" },
  "46": { code: "46", name: "Lot" },
  "47": { code: "47", name: "Lot-et-Garonne" },
  "48": { code: "48", name: "Lozère" },
  "49": { code: "49", name: "Maine-et-Loire" },
  "50": { code: "50", name: "Manche" },
  "51": { code: "51", name: "Marne" },
  "52": { code: "52", name: "Haute-Marne" },
  "53": { code: "53", name: "Mayenne" },
  "54": { code: "54", name: "Meurthe-et-Moselle" },
  "55": { code: "55", name: "Meuse" },
  "56": { code: "56", name: "Morbihan" },
  "57": { code: "57", name: "Moselle" },
  "58": { code: "58", name: "Nièvre" },
  "59": { code: "59", name: "Nord" },
  "60": { code: "60", name: "Oise" },
  "61": { code: "61", name: "Orne" },
  "62": { code: "62", name: "Pas-de-Calais" },
  "63": { code: "63", name: "Puy-de-Dôme" },
  "64": { code: "64", name: "Pyrénées-Atlantiques" },
  "65": { code: "65", name: "Hautes-Pyrénées" },
  "66": { code: "66", name: "Pyrénées-Orientales" },
  "67": { code: "67", name: "Bas-Rhin" },
  "68": { code: "68", name: "Haut-Rhin" },
  "69": { code: "69", name: "Rhône" },
  "70": { code: "70", name: "Haute-Saône" },
  "71": { code: "71", name: "Saône-et-Loire" },
  "72": { code: "72", name: "Sarthe" },
  "73": { code: "73", name: "Savoie" },
  "74": { code: "74", name: "Haute-Savoie" },
  "75": { code: "75", name: "Paris" },
  "76": { code: "76", name: "Seine-Maritime" },
  "77": { code: "77", name: "Seine-et-Marne" },
  "78": { code: "78", name: "Yvelines" },
  "79": { code: "79", name: "Deux-Sèvres" },
  "80": { code: "80", name: "Somme" },
  "81": { code: "81", name: "Tarn" },
  "82": { code: "82", name: "Tarn-et-Garonne" },
  "83": { code: "83", name: "Var" },
  "84": { code: "84", name: "Vaucluse" },
  "85": { code: "85", name: "Vendée" },
  "86": { code: "86", name: "Vienne" },
  "87": { code: "87", name: "Haute-Vienne" },
  "88": { code: "88", name: "Vosges" },
  "89": { code: "89", name: "Yonne" },
  "90": { code: "90", name: "Territoire de Belfort" },
  "91": { code: "91", name: "Essonne" },
  "92": { code: "92", name: "Hauts-de-Seine" },
  "93": { code: "93", name: "Seine-Saint-Denis" },
  "94": { code: "94", name: "Val-de-Marne" },
  "95": { code: "95", name: "Val-d'Oise" },
  "99": { code: "99", name: "Etranger" },
  "971": { code: "971", name: "Guadeloupe" },
  "972": { code: "972", name: "Martinique" },
  "973": { code: "973", name: "Guyane" },
  "974": { code: "974", name: "La Réunion" },
  "976": { code: "976", name: "Mayotte" },
};

export const departementsList = [
  { code: "01", name: "Ain" },
  { code: "02", name: "Aisne" },
  { code: "03", name: "Allier" },
  { code: "04", name: "Alpes-de-Haute-Provence" },
  { code: "05", name: "Hautes-Alpes" },
  { code: "06", name: "Alpes-Maritimes" },
  { code: "07", name: "Ardèche" },
  { code: "08", name: "Ardennes" },
  { code: "09", name: "Ariège" },
  { code: "10", name: "Aube" },
  { code: "11", name: "Aude" },
  { code: "12", name: "Aveyron" },
  { code: "13", name: "Bouches-du-Rhône" },
  { code: "14", name: "Calvados" },
  { code: "15", name: "Cantal" },
  { code: "16", name: "Charente" },
  { code: "17", name: "Charente-Maritime" },
  { code: "18", name: "Cher" },
  { code: "19", name: "Corrèze" },
  { code: "2A", name: "Corse-du-Sud" },
  { code: "2B", name: "Haute-Corse" },
  { code: "21", name: "Côte-d'Or" },
  { code: "22", name: "Côtes-d'Armor" },
  { code: "23", name: "Creuse" },
  { code: "24", name: "Dordogne" },
  { code: "25", name: "Doubs" },
  { code: "26", name: "Drôme" },
  { code: "27", name: "Eure" },
  { code: "28", name: "Eure-et-Loir" },
  { code: "29", name: "Finistère" },
  { code: "30", name: "Gard" },
  { code: "31", name: "Haute-Garonne" },
  { code: "32", name: "Gers" },
  { code: "33", name: "Gironde" },
  { code: "34", name: "Hérault" },
  { code: "35", name: "Ille-et-Vilaine" },
  { code: "36", name: "Indre" },
  { code: "37", name: "Indre-et-Loire" },
  { code: "38", name: "Isère" },
  { code: "39", name: "Jura" },
  { code: "40", name: "Landes" },
  { code: "41", name: "Loir-et-Cher" },
  { code: "42", name: "Loire" },
  { code: "43", name: "Haute-Loire" },
  { code: "44", name: "Loire-Atlantique" },
  { code: "45", name: "Loiret" },
  { code: "46", name: "Lot" },
  { code: "47", name: "Lot-et-Garonne" },
  { code: "48", name: "Lozère" },
  { code: "49", name: "Maine-et-Loire" },
  { code: "50", name: "Manche" },
  { code: "51", name: "Marne" },
  { code: "52", name: "Haute-Marne" },
  { code: "53", name: "Mayenne" },
  { code: "54", name: "Meurthe-et-Moselle" },
  { code: "55", name: "Meuse" },
  { code: "56", name: "Morbihan" },
  { code: "57", name: "Moselle" },
  { code: "58", name: "Nièvre" },
  { code: "59", name: "Nord" },
  { code: "60", name: "Oise" },
  { code: "61", name: "Orne" },
  { code: "62", name: "Pas-de-Calais" },
  { code: "63", name: "Puy-de-Dôme" },
  { code: "64", name: "Pyrénées-Atlantiques" },
  { code: "65", name: "Hautes-Pyrénées" },
  { code: "66", name: "Pyrénées-Orientales" },
  { code: "67", name: "Bas-Rhin" },
  { code: "68", name: "Haut-Rhin" },
  { code: "69", name: "Rhône" },
  { code: "70", name: "Haute-Saône" },
  { code: "71", name: "Saône-et-Loire" },
  { code: "72", name: "Sarthe" },
  { code: "73", name: "Savoie" },
  { code: "74", name: "Haute-Savoie" },
  { code: "75", name: "Paris" },
  { code: "76", name: "Seine-Maritime" },
  { code: "77", name: "Seine-et-Marne" },
  { code: "78", name: "Yvelines" },
  { code: "79", name: "Deux-Sèvres" },
  { code: "80", name: "Somme" },
  { code: "81", name: "Tarn" },
  { code: "82", name: "Tarn-et-Garonne" },
  { code: "83", name: "Var" },
  { code: "84", name: "Vaucluse" },
  { code: "85", name: "Vendée" },
  { code: "86", name: "Vienne" },
  { code: "87", name: "Haute-Vienne" },
  { code: "88", name: "Vosges" },
  { code: "89", name: "Yonne" },
  { code: "90", name: "Territoire de Belfort" },
  { code: "91", name: "Essonne" },
  { code: "92", name: "Hauts-de-Seine" },
  { code: "93", name: "Seine-Saint-Denis" },
  { code: "94", name: "Val-de-Marne" },
  { code: "95", name: "Val-d'Oise" },
  { code: "99", name: "Etranger" },
  { code: "971", name: "Guadeloupe" },
  { code: "972", name: "Martinique" },
  { code: "973", name: "Guyane" },
  { code: "974", name: "La Réunion" },
  { code: "976", name: "Mayotte" },
];
