export enum DOCUMENT_TYPES {
  DECA = "DECA",
  OCAPIAT = "OCAPIAT",
  CONSTRUCTYS = "CONSTRUCTYS",
  VOEUX_PARCOURSUP_MAI_2023 = "Voeux Parcoursup Mai 2023",
  VOEUX_AFFELNET_MAI_2023 = "Voeux Affelnet Mai 2023",
  VOEUX_AFFELNET_JUIN_2023 = "Voeux Affelnet Juin 2023",
}
