- block:
    - name: Add mongodb backup cron
      cron:
        name: "backup mongodb each day at 04h00"
        minute: "0"
        hour: "4"
        job: "bash /opt/bal/tools/mongodb/backup-mongodb.sh >> /var/log/backup-mongodb.log 2>&1; /opt/bal/tools/monitoring/export-cron-status-prom.sh -c 'MongoDB Backup' -v $?"

    - name: Add metabase backup cron"
      become: true
      cron:
        name: "backup metabase"
        minute: "20"
        hour: "0"
        job: "bash /opt/bal/tools/metabase/backup-metabase.sh >> /var/log/backup-metabase.log 2>&1; /opt/bal/tools/monitoring/export-cron-status-prom.sh -c 'Metabase Backup' -v $?"

  when: backup_cron|bool == true
