- name: Check if SSL certificate has been generated
  stat: path=/opt/bal/data/ssl/privkey.pem
  register: ssl

- name: Generate SSL certificate with LetsEncrypt
  shell: "bash /opt/bal/tools/ssl/generate-certificate.sh {{dns_name}}"
  register: output
  when: ssl.stat.exists == False

- debug:
    var: output
  when: ssl.stat.exists == True

- name: Add cron to ensure SSL certificate will be renewed
  ansible.builtin.cron:
    name: "renew-certificate"
    minute: "0"
    hour: "2"
    weekday: "1"
    job: "bash /opt/bal/tools/ssl/renew-certificate.sh {{dns_name}} >> /var/log/cron.log 2>&1; /opt/bal/tools/monitoring/export-cron-status-prom.sh -c 'Renew certificate' -v $?"
