---
- hosts: all
  become: true
  gather_facts: false
  vars_files:
    - "../vault/vault.yml"
  tasks:
    - name: check du docker network
      ansible.builtin.shell:
        chdir: /opt/bal
        cmd: docker network ls --filter name=bal_network -q
      register: network
    - debug:
        var: network

    - name: création du docker network
      ansible.builtin.shell:
        chdir: /opt/bal
        cmd: docker network create -d overlay --attachable bal_network
      when: network.stdout == ""

    - name: copy server env file
      ansible.builtin.template:
        src: "{{ item }}"
        dest: "/opt/bal/.env_server"
      with_fileglob:
        - "../.env_server"

    - name: copy du fichier docker compose
      ansible.builtin.template:
        src: "{{ item }}"
        dest: "/opt/bal/docker-compose.yml"
      with_fileglob:
        - "../docker-compose.yml"

    - name: copy du fichier recette docker compose
      ansible.builtin.template:
        src: "{{ item }}"
        dest: "/opt/bal/docker-compose.recette.yml"
      with_fileglob:
        - "../docker-compose.recette.yml"
      when: env_type == 'recette'

    - name: Récupération des images docker
      shell:
        chdir: /opt/bal
        cmd: "sudo docker compose pull"

    - name: Récupération du status de la stack
      shell:
        chdir: /opt/bal
        cmd: docker stack ls --format json
      register: stack_status

    - name: Récupération du status des migrations
      shell:
        chdir: /opt/bal
        cmd: "sudo /opt/bal/tools/migrations/migrations-status.sh"
      register: migration_status_output
      when: stack_status.stdout != ""

    - name: "Shutdown processor"
      shell:
        chdir: /opt/bal
        cmd: "sudo docker service scale bal_processor=0"
      when:
        - stack_status.stdout != ""
        - migration_status_output.stdout_lines[-2] != 'migrations-status=synced'

    - name: "Activation du mode maintenance pour effectuer la migration"
      shell:
        chdir: /opt/bal
        cmd: "sudo /opt/bal/tools/maintenance/maintenance-on.sh"
      when:
        - stack_status.stdout != ""
        - migration_status_output.stdout_lines[-2] != 'migrations-status=synced'

    - name: "Shutdown server"
      shell:
        chdir: /opt/bal
        cmd: "sudo docker service scale bal_server=0"
      when:
        - stack_status.stdout != ""
        - migration_status_output.stdout_lines[-2] != 'migrations-status=synced'

    - name: Lancement des migrations
      shell:
        chdir: /opt/bal
        cmd: "sudo /opt/bal/tools/migrations/migrations-up.sh"
      when:
        - stack_status.stdout != ""
        - migration_status_output.stdout_lines[-2] != 'migrations-status=synced'

    - name: Lancement de l'application {{env_type}}
      shell:
        chdir: /opt/bal
        cmd: "sudo docker stack deploy -c docker-compose.yml -c docker-compose.recette.yml bal"
      register: docker_deploy_output
      when: env_type == 'recette'

    - name: Lancement de l'application {{env_type}}
      shell:
        chdir: /opt/bal
        cmd: "sudo docker stack deploy -c docker-compose.yml bal"
      register: docker_deploy_output
      when: env_type == 'production'

    - debug:
        var: docker_deploy_output

    - name: Attente du deploiement
      shell:
        chdir: /opt/bal
        cmd: "sudo docker run --rm -v /var/run/docker.sock:/var/run/docker.sock sudobmitch/docker-stack-wait bal"
      timeout: 900

    - name: "Setup de la Metabase"
      shell:
        chdir: /opt/bal
        cmd: "sudo /opt/bal/tools/metabase/setup-metabase.sh"
      timeout: 900

    - name: "Prune Docker"
      shell:
        chdir: /opt/bal
        cmd: "sudo docker system prune --all --force"

    - name: "Désactivation du mode maintenance"
      shell:
        chdir: /opt/bal
        cmd: "sudo /opt/bal/tools/maintenance/maintenance-off.sh"
