version: "2.4"
services:
  server_LOCAL_VERSION:
    image: "ghcr.io/mission-apprentissage/mna_bal_server:LOCAL_VERSION"
    container_name: bal_server_LOCAL_VERSION
    restart: unless-stopped
    mem_limit: 1g
    networks:
      - bal_network
    depends_on:
      - mongodb
    environment:
      - VIRTUAL_HOST=LOCAL_VERSION.bal-preview.apprentissage.beta.gouv.fr
      - VIRTUAL_PATH=/api
      - VIRTUAL_PORT=5000
      - LETSENCRYPT_HOST=LOCAL_VERSION.bal-preview.apprentissage.beta.gouv.fr
      - LETSENCRYPT_EMAIL=misson.apprentissage.devops@gmail.com
    env_file: .env_server
    volumes:
      - /opt/bal/data/server:/data

  ui_LOCAL_VERSION:
    image: "ghcr.io/mission-apprentissage/mna_bal_ui:LOCAL_VERSION"
    container_name: bal_ui_LOCAL_VERSION
    restart: unless-stopped
    mem_limit: 256m
    networks:
      - bal_network
    depends_on:
      - server_LOCAL_VERSION
    environment:
      - VIRTUAL_HOST=LOCAL_VERSION.bal-preview.apprentissage.beta.gouv.fr
      - VIRTUAL_PATH=/
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=LOCAL_VERSION.bal-preview.apprentissage.beta.gouv.fr
      - LETSENCRYPT_EMAIL=misson.apprentissage.devops@gmail.com
    env_file: .env_ui

  processor_LOCAL_VERSION:
    image: "ghcr.io/mission-apprentissage/mna_bal_server:LOCAL_VERSION"
    container_name: bal_processor_LOCAL_VERSION
    command: ["yarn", "cli", "processor"]
    mem_limit: 1g
    restart: unless-stopped
    networks:
      - bal_network
    depends_on:
      - mongodb
    env_file: .env_server
    volumes:
      - /opt/bal/data/server:/data


networks:
  bal_network:
    name: bal_network
