#!/usr/bin/env bash

set -euo pipefail

export SCRIPT_DIR="$(dirname -- "$( readlink -f -- "$0"; )")"
export ROOT_DIR="$(dirname "${SCRIPT_DIR}")"

source "${SCRIPT_DIR}/commands.sh"

################################################################################
################################################################################
# Main program                                                                 #
################################################################################
################################################################################

readonly command=${1:-}
if [ -z "$command" ]; then
  Help
fi;
shift

if [[ `command -v $command` != $command ]]; then
  echo "Err: Command '$command' not found"
  echo
  Help
fi;

$command "$@"
