#Override containers for azure environments
version: "2.4"
services:
  reverse_proxy:
    environment:
      - SERVER_NAME={{dns_name}}
      - NGINX_ALWAYS_TLS_REDIRECT=true
      - PROXY_SSL_CERT=/ssl/fullchain.pem
      - PROXY_SSL_CERT_KEY=/ssl/privkey.pem
    volumes:
      - /opt/bal/data/nginx:/data
      - /opt/bal/data/ssl:/ssl:ro
      - /opt/bal/.overrides/reverse_proxy/includes:/etc/nginx/templates/includes/env

  server:
    volumes:
      - /opt/bal/data/server:/data

  mongodb:
    command: mongod --auth
    volumes:
      - /opt/bal/data/mongodb/db:/data/db
      - /opt/bal/data/mongodb/configdb:/data/configdb
      - /opt/bal/data/mongodb/backups:/data/backups-legacy
      - /opt/bal/.overrides/mongodb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
    # ports:
    #   - "127.0.0.1:27017:27017"

  metabase:
    image: metabase/metabase:v0.45.3
    container_name: bal_metabase
    mem_limit: 2g
    volumes:
      - /opt/bal/data/metabase:/data/metabase
      - /opt/bal/backups/metabase:/data/backups
    depends_on:
      - mongodb
    environment:
      JAVA_TIMEZONE: Europe/Paris
      MB_DB_FILE: /data/metabase/metabase.db
      MB_SITE_LOCALE: fr
      MB_SITE_URL: http://0.0.0.0/metabase
    restart: always
    networks:
      - bal_network

  nodeexporter:
    image: prom/node-exporter:v1.5.0
    restart: unless-stopped
    container_name: nodeexporter
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    networks:
      - bal_network

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.46.0
    restart: unless-stopped
    container_name: cadvisor
    privileged: true
    devices:
      - /dev/kmsg
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    networks:
      - bal_network
