import { z } from "zod/v4-mini";

const etablissementFormateurSchema = z.object({
  etablissement_formateur_id: z.nullish(z.string()),
  etablissement_formateur_siret: z.nullish(z.string()),
  etablissement_formateur_enseigne: z.nullish(z.string()),
  etablissement_formateur_uai: z.nullish(z.string()),
  etablissement_formateur_type: z.nullish(z.string()),
  etablissement_formateur_conventionne: z.nullish(z.string()),
  etablissement_formateur_declare_prefecture: z.nullish(z.string()),
  etablissement_formateur_datadock: z.nullish(z.string()),
  etablissement_formateur_adresse: z.nullish(z.string()),
  etablissement_formateur_code_postal: z.nullish(z.string()),
  etablissement_formateur_code_commune_insee: z.nullish(z.string()),
  etablissement_formateur_localite: z.nullish(z.string()),
  etablissement_formateur_complement_adresse: z.nullish(z.string()),
  etablissement_formateur_cedex: z.nullish(z.string()),
  etablissement_formateur_entreprise_raison_sociale: z.nullish(z.string()),
  geo_coordonnees_etablissement_formateur: z.nullish(z.string()),
  etablissement_formateur_region: z.nullish(z.string()),
  etablissement_formateur_num_departement: z.nullish(z.string()),
  etablissement_formateur_nom_departement: z.nullish(z.string()),
  etablissement_formateur_nom_academie: z.nullish(z.string()),
  etablissement_formateur_num_academie: z.nullish(z.string()),
  etablissement_formateur_siren: z.nullish(z.string()),
  etablissement_formateur_courriel: z.nullish(z.string()),
  etablissement_formateur_published: z.nullish(z.boolean()),
  etablissement_formateur_catalogue_published: z.nullish(z.boolean()),
  rncp_etablissement_formateur_habilite: z.nullish(z.boolean()),
  etablissement_formateur_date_creation: z.nullish(z.string()),
});
const etablissementGestionnaireSchema = z.object({
  etablissement_gestionnaire_id: z.nullish(z.string()),
  etablissement_gestionnaire_siret: z.nullish(z.string()),
  etablissement_gestionnaire_enseigne: z.nullish(z.string()),
  etablissement_gestionnaire_uai: z.nullish(z.string()),
  etablissement_gestionnaire_type: z.nullish(z.string()),
  etablissement_gestionnaire_conventionne: z.nullish(z.string()),
  etablissement_gestionnaire_declare_prefecture: z.nullish(z.string()),
  etablissement_gestionnaire_datadock: z.nullish(z.string()),
  etablissement_gestionnaire_adresse: z.nullish(z.string()),
  etablissement_gestionnaire_code_postal: z.nullish(z.string()),
  etablissement_gestionnaire_code_commune_insee: z.nullish(z.string()),
  etablissement_gestionnaire_localite: z.nullish(z.string()),
  etablissement_gestionnaire_complement_adresse: z.nullish(z.string()),
  etablissement_gestionnaire_cedex: z.nullish(z.string()),
  etablissement_gestionnaire_entreprise_raison_sociale: z.nullish(z.string()),
  geo_coordonnees_etablissement_gestionnaire: z.nullish(z.string()),
  etablissement_gestionnaire_region: z.nullish(z.string()),
  etablissement_gestionnaire_num_departement: z.nullish(z.string()),
  etablissement_gestionnaire_nom_departement: z.nullish(z.string()),
  etablissement_gestionnaire_nom_academie: z.nullish(z.string()),
  etablissement_gestionnaire_num_academie: z.nullish(z.string()),
  etablissement_gestionnaire_siren: z.nullish(z.string()),
  etablissement_gestionnaire_courriel: z.nullish(z.string()),
  etablissement_gestionnaire_published: z.nullish(z.boolean()),
  etablissement_gestionnaire_catalogue_published: z.nullish(z.boolean()),
  rncp_etablissement_gestionnaire_habilite: z.nullish(z.boolean()),
  etablissement_gestionnaire_date_creation: z.nullish(z.string()),
});
const etablissementReferenceSchema = z.object({
  etablissement_reference: z.nullish(z.string()),
  etablissement_reference_published: z.nullish(z.boolean()),
  etablissement_reference_habilite_rncp: z.nullish(z.boolean()),
  etablissement_reference_certifie_qualite: z.nullish(z.boolean()),
  etablissement_reference_date_creation: z.nullish(z.string()),
});
const stringOrArraySchema = z.union([z.string(), z.array(z.string())]);

export const zFormationCatalogue = z.object({
  _id: z.string(),
  cle_ministere_educatif: z.string(),
  cfd: z.string(),
  cfd_specialite: z.nullish(z.string()),
  cfa_outdated: z.nullish(z.boolean()),
  cfd_date_fermeture: z.nullish(z.string()),
  cfd_entree: z.nullish(z.string()),
  mef_10_code: z.nullish(z.string()),
  mefs_10: z.nullish(z.array(z.string())),
  nom_academie: z.nullish(z.string()),
  num_academie: z.nullish(z.string()),
  code_postal: z.nullish(z.string()),
  code_commune_insee: z.nullish(z.string()),
  num_departement: z.nullish(z.string()),
  nom_departement: z.nullish(z.string()),
  region: z.nullish(z.string()),
  localite: z.nullish(z.string()),
  uai_formation: z.nullish(z.string()),
  nom: z.nullish(z.string()),
  intitule_long: z.nullish(z.string()),
  intitule_court: z.nullish(z.string()),
  diplome: z.nullish(z.string()),
  niveau: z.nullish(z.string()),
  onisep_url: z.nullish(z.string()),
  onisep_intitule: z.nullish(z.string()),
  onisep_libelle_poursuite: z.nullish(z.string()),
  onisep_lien_site_onisepfr: z.nullish(z.string()),
  onisep_discipline: z.nullish(z.string()),
  onisep_domaine_sousdomaine: z.nullish(z.string()),
  rncp_code: z.nullish(z.string()),
  rncp_intitule: z.nullish(z.string()),
  rncp_eligible_apprentissage: z.nullish(z.boolean()),
  rncp_details: z.nullish(z.record(z.string(), z.unknown())),
  rome_codes: z.nullish(z.array(z.string())),
  capacite: z.nullish(z.string()),
  duree: z.nullish(z.string()),
  annee: z.nullish(z.string()),
  email: z.nullish(z.string()),
  parcoursup_statut: z.nullish(z.string()),
  parcoursup_error: z.nullish(z.string()),
  parcoursup_statut_history: z.nullish(z.record(z.string(), z.unknown())),
  parcoursup_reference: z.nullish(z.boolean()),
  parcoursup_a_charger: z.nullish(z.boolean()),
  parcoursup_id: z.nullish(z.string()),
  affelnet_reference: z.nullish(z.boolean()),
  affelnet_a_charger: z.nullish(z.boolean()),
  affelnet_statut: z.nullish(z.string()),
  affelnet_statut_history: z.nullish(z.record(z.string(), z.unknown())),
  source: z.nullish(z.string()),
  commentaires: z.nullish(z.string()),
  opcos: z.nullish(z.array(z.string())),
  info_opcos: z.nullish(z.number()),
  info_opcos_intitule: z.nullish(z.string()),
  published: z.nullish(z.boolean()),
  rco_published: z.nullish(z.boolean()),
  draft: z.nullish(z.boolean()),
  created_at: z.nullish(z.string()),
  updates_history: z.nullish(z.record(z.string(), z.unknown())),
  last_update_at: z.nullish(z.string()),
  last_update_who: z.nullish(z.string()),
  to_update: z.nullish(z.boolean()),
  update_error: z.nullish(z.string()),
  lieu_formation_geo_coordonnees: z.nullish(z.string()),
  lieu_formation_geopoint: z.nullish(z.unknown()),
  lieu_formation_adresse: z.nullish(z.string()),
  lieu_formation_adresse_computed: z.nullish(z.string()),
  lieu_formation_siret: z.nullish(z.string()),
  id_rco_formation: z.nullish(z.string()),
  id_formation: z.nullish(z.string()),
  id_action: z.nullish(z.string()),
  ids_action: z.nullish(z.array(z.string())),
  id_certifinfo: z.nullish(z.string()),
  tags: z.nullish(z.array(z.string())),
  libelle_court: z.nullish(stringOrArraySchema),
  niveau_formation_diplome: z.nullish(z.string()),
  affelnet_infos_offre: z.nullish(z.string()),
  affelnet_code_nature: z.nullish(z.string()),
  affelnet_secteur: z.nullish(z.string()),
  affelnet_raison_depublication: z.nullish(z.string()),
  bcn_mefs_10: z.nullish(z.record(z.string(), z.unknown())),
  editedFields: z.nullish(z.record(z.string(), z.unknown())),
  parcoursup_raison_depublication: z.nullish(z.string()),
  distance_lieu_formation_etablissement_formateur: z.nullish(z.number()),
  niveau_entree_obligatoire: z.nullish(z.number()),
  entierement_a_distance: z.nullish(z.boolean()),
  catalogue_published: z.nullish(z.boolean()),
  contenu: z.nullish(z.string()),
  objectif: z.nullish(z.string()),
  date_debut: z.nullish(z.array(z.string())),
  date_fin: z.nullish(z.array(z.string())),
  modalites_entrees_sorties: z.nullish(z.array(z.boolean())),
  num_tel: z.nullish(z.string()),
  distance: z.nullish(z.number()),
  ...etablissementFormateurSchema.shape,
  ...etablissementGestionnaireSchema.shape,
  ...etablissementReferenceSchema.shape,
});
