name: Deployment
on:
  workflow_dispatch:
    inputs:
      environment:
        description: The environment to deploy to
        type: choice
        required: true
        options:
          - production
      user:
        description: The server user to connect
        type: string
        required: true
      pwd:
        description: The server pwd to connect
        type: string
        required: true
      app_version:
        description: app version
        type: string
        required: true
        default: 1.6.3
    secrets:
      SSH_PRIVATE_KEY:
        description: SSH private key
        required: true
      SSH_KNOWN_HOSTS:
        description: SSH known hosts list
        required: true
      SLACK_WEBHOOK:
        description: Slack webhook URL
        required: true

jobs:
  deploy:
    name: Deploy ${{ inputs.app_version }} on ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Notify new deployment on Slack
        uses: ravsamhq/notify-slack-action@v2
        if: always()
        with:
          status: ${{ job.status }}
          notification_title: "Déploiement ${{ inputs.app_version }} en ${{ inputs.environment }} initié..."
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

      - name: Checkout project
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          name: github_actions
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
          config: |
            Host 51.68.44.237
              HostName 51.68.44.237
              User ${{inputs.user}}
              IdentityFile ~/.ssh/github_actions

      - name: Create vault pwd file
        run: echo ${{ secrets.VAULT_PWD }} > .infra/.vault_pwd.txt

      - name: Run playbook
        run: |
          SECRET_VALUE=$(cat $GITHUB_EVENT_PATH | jq -r '.inputs.pwd' )
          echo "::add-mask::$SECRET_VALUE"
          ansible-playbook -i ".infra/env.ini" --limit "${{ inputs.environment }}" --vault-password-file=".infra/.vault_pwd.txt" --extra-vars "app_version=${{ inputs.app_version }} ansible_sudo_pass=$SECRET_VALUE" ".infra/playbooks/deploy.yml" --user ${{inputs.user}}

      - name: Notify failure on Slack
        uses: ravsamhq/notify-slack-action@v2
        if: always()
        with:
          status: ${{ job.status }}
          notification_title: "Le déploiement ${{ inputs.app_version }} en ${{ inputs.environment }} a échoué"
          notify_when: "failure"
          mention_groups: "!channel"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

      - name: Notify success on Slack
        uses: ravsamhq/notify-slack-action@v2
        if: always()
        with:
          status: ${{ job.status }}
          notification_title: "Déploiement ${{ inputs.app_version }} en ${{ inputs.environment }} terminé avec succès"
          notify_when: "success"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
