name: Save/Load deps
on:
  workflow_call:
jobs:
  caching:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Creates empty env-vars server
        run: touch .env_server

      - name: Creates empty env-vars ui
        run: touch .env_ui

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64

      # - uses: actions/cache@v3
      #   with:
      #     path: |
      #       node_modules
      #       ui/node_modules
      #       server/node_modules
      #       yarn.lock
      #       /tmp/.build
      #     key: ${{ runner.os }}-deps-${{ hashFiles('**/yarn.lock') }}
      #     restore-keys: |
      #       ${{ runner.os }}-deps-${{ hashFiles('**/yarn.lock') }}

      # - id: should-cache
      #   run: |
      #     if [ ! -d /tmp/.build ]
      #     then
      #       echo "build=yes" >> $GITHUB_OUTPUT
      #     fi
      #   shell: bash

      - name: Build
        # if: ${{ contains(steps.should-cache.outputs.build, 'yes') }}
        run: make ci-install
        shell: bash
