name: Save/Load deps
on:
  workflow_call:
jobs:
  caching:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Creates empty env-vars server
        run: touch .env_server

      - name: Creates empty env-vars ui
        run: touch .env_ui

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64

      - uses: actions/cache@v3
        id: cache
        with:
          path: /tmp/docker_images.tgz
          key: deps-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            docker-${{ hashFiles('**/yarn.lock') }}
            docker-

      - name: Build
        if: steps.cache.outputs.cache-hit == 'true'
        run: docker load < /tmp/docker_images.tgz
        shell: bash

      - name: Build
        run: make ci-install
        shell: bash

      - name: Save Image to cache
        run: docker save bal-repo_modules bal-reverse_proxy bal-server-test | gzip > /tmp/docker_images.tgz
