name: Save/Load deps
on:
  workflow_call:
jobs:
  caching:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: actions/cache@v3
        with:
          path: |
            node_modules
            ui/node_modules
            server/node_modules
            yarn.lock
            /tmp/.build
          key: ${{ runner.os }}-deps-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-deps-${{ hashFiles('**/yarn.lock') }}

      - id: should-cache
        run: |
          if [ ! -d /tmp/.build ]
          then
            echo "build=yes" >> $GITHUB_OUTPUT
          fi
        shell: bash

      - name: Build
        if: ${{ contains(steps.should-cache.outputs.build, 'yes') }}
        run: |
          yarn plugin import workspace-tools
          yarn workspaces focus --all &> /dev/null
          sed -i '/**\/node_modules/d' .dockerignore
          sed -i '/**\/dist/d' .dockerignore
          sed -i '/yarn\.lock/d' .dockerignore
          docker build . --tag mna_bal_deps_installer:local
          mkdir -p /tmp/.build
          docker save -o /tmp/.build/mna_bal_deps_installer.tar mna_bal_deps_installer:local
        shell: bash
