name: Clean Previews
on:
  schedule:
    - cron: "0 0 * * *"

concurrency:
  group: ${{ github.workflow }}

jobs:
  cleanup:
    name: Clean Previews
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          name: github_actions
          key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
          config: |
            Host *
              IdentityFile ~/.ssh/github_actions

      - name: Create vault pwd file
        run: echo ${{ secrets.VAULT_PWD }} > .infra/.vault_pwd.txt

      - name: Install jmespath
        run: |
          sudo pipx inject ansible-core jmespath

      - name: Run playbook
        run: |
          ansible-playbook -i ".infra/env.ini" --limit preview --vault-password-file=".infra/.vault_pwd.txt" --extra-vars "ansible_sudo_pass=${{ secrets.DEPLOY_PASS }}" ".infra/playbooks/preview_cleanup.yml" --user ${{ secrets.DEPLOY_USERNAME }}
