name: Publish
on:
  push:
    branches: [feat/9-ajouter-le-monitoring]

jobs:
  publish-ghcr:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build the hello-docker Docker image
        run: |
          docker build ./reverse_proxy --tag ghcr.io/mission-apprentissage/mna-bal:1.3.0
          docker run ghcr.io/mission-apprentissage/mna-bal:1.3.0
          docker push ghcr.io/mission-apprentissage/mna-bal:1.3.0
